<a href="https://colab.research.google.com/github/Mysterio-maker/TO-STUDY-HOW-TO-LOAD-AND-CREATE-DATASET-IN-PYTHON/blob/main/EXPERIMENT_10%3D_CREATE_AND_LOAD_DATASETipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Experiment - 10
# Title - Create dataset and load dataset

##Name- Amey waghmare
##PRN- 25070123009
##Batch- A1

In [ ]:
import pandas as pd

data = {
    "Roll_no": [1, 2, 3, 4, 5],
    "Gender": ["male", "female", "male", "female", "male"],
    "Department": ["ENTC", "CS", "IT", "AI ML", "ELECTRICAL"],
    "CGPA": [8.5, 9.2, 7.8, 9.5, 8.9]
}

df = pd.DataFrame(data)

df.to_csv("student_data.csv", index=False)

In [ ]:
df.shape

(5, 4)

In [ ]:
import pandas as pd

data = {
    "Roll_no": [1, 2, 3, 4, 5],
    "Gender": ["male", "female", "male", "female", "male"],
    "Department": ["ENTC", "CS", "IT", "AI ML", "ELECTRICAL"],
    "CGPA": [8.5, 9.2, 7.8, 9.5, 8.9]
}

df = pd.DataFrame(data)

df.to_excel("student_data.xlsx", index=False)

In [ ]:
#access the informarion about Department column
df["Department"]

0          ENTC
1            CS
2            IT
3         AI ML
4    ELECTRICAL
Name: Department, dtype: object

In [ ]:
# Access information of roll no 3

roll_no_3 = df[df["Roll_no"] == 3]
print(roll_no_3)

   Roll_no Gender Department  CGPA
2        3   male         IT   7.8

In [ ]:
# Find out data types of each column

df.dtypes

Roll_no         int64
Gender         object
Department     object
CGPA          float64
dtype: object

In [ ]:
# Perform mean,median and mode operation

print("Mean:", df["CGPA"].mean())
print("Median:", df["CGPA"].median())
print("Mode:", df["CGPA"].mode()[0])

Mean: 8.78
Median: 8.9
Mode: 7.8

In [ ]:
# Insert a new column grade

df["Grade"] = ["A", "A+", "B", "A+", "A"]

print(df)

   Roll_no  Gender  Department  CGPA Grade
0        1    male        ENTC   8.5     A
1        2  female          CS   9.2    A+
2        3    male          IT   7.8     B
3        4  female       AI ML   9.5    A+
4        5    male  ELECTRICAL   8.9     A

In [ ]:
# Delete Gender column

df = df.drop("Gender", axis=1)

print(df)

   Roll_no  Department  CGPA Grade
0        1        ENTC   8.5     A
1        2          CS   9.2    A+
2        3          IT   7.8     B
3        4       AI ML   9.5    A+
4        5  ELECTRICAL   8.9     A

In [ ]:
#CGPA of topper
topper_cgpa = df.loc[df["CGPA"].idxmax(), "CGPA"]
df

   Roll_no  Department  CGPA Grade
0        1        ENTC   8.5     A
1        2          CS   9.2    A+
2        3          IT   7.8     B
3        4       AI ML   9.5    A+
4        5  ELECTRICAL   8.9     A

In [ ]:
#CGPA of roll no 2
roll_no_2_cgpa = df.loc[df["Roll_no"] == 2, "CGPA"].values
df

   Roll_no  Department  CGPA Grade
0        1        ENTC   8.5     A
1        2          CS   9.2    A+
2        3          IT   7.8     B
3        4       AI ML   9.5    A+
4        5  ELECTRICAL   8.9     A

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv('/content/Cars93.csv')
df

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0

In [ ]:
df.head()

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0

In [ ]:
df.tail()

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0